version: "3.8"

services:
  # Aplicação Flask
  app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000" # Mapeando a porta do contêiner para a máquina host
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DB=gestao_estoque
    depends_on:
      - db
    volumes:
      - .:/app

  # Banco de dados MySQL
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gestao_estoque
    ports:
      - "3308:3306" # Mapeando a porta 3308 do contêiner para a máquina host
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
